### PR TITLE
Updated Sematext 0.6.x and 1.x documentation

### PR DESCRIPTION
**Pull request by qkoshelev**

### CODE REVIEW

**Comment by otisg** [comment]
Is this ready for merge now @qkoshelev & @dpsoft ?

**Comment by dpsoft** [comment]
@qkoshelev @otisg LGTM! @ivantopo WDYT?

**Comment by ivantopo** [comment]
Thanks for the help @otisg and @qkoshelev. I think we can publish this release by the end of day!

**Comment by otisg** [comment]
@ivantopo I looked on http://kamon.io/documentation/1.x/get-started/ but couldn't find SPM.  Were you able to publish it?

**Comment by ivantopo** [comment]
Hey guys! I just pushed the new website with the SPM docs included.

**Pull request merged**
