### PR TITLE
Adjusted spm documentation

### PR DESCRIPTION
**Pull request by qkoshelev**

### CODE REVIEW

**Comment by otisg** [comment]
@dpsoft or @ivantopo this is a trivial merge.  Do you think you could merge before your next release, which I think is imminent?

**Comment by dpsoft** [comment]
@otisg we will make a new release this weekend. Done!!!

**Comment by otisg** [comment]
Great, thanks.  Do you know when the new release will be out @dpsoft ?

**Comment by dpsoft** [comment]
hey @otisg I've just published the release but in some minutes we will make the announcement. ;).
```kamon-spm``` is already in maven repository: http://repo1.maven.org/maven2/io/kamon/kamon-spm_2.11/0.6.2/

**Pull request merged**
